from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_PHASE1_BUILDER_PROMPT.md")

lines = []
lines.append("# Vancomyzer Phase 1 Builder Prompt")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")
lines.append("## Purpose")
lines.append("Provide a single implementation prompt that can be given to a builder agent or coding assistant to start Phase 1 website implementation.")
lines.append("")

lines.append("## Builder brief")
lines.append("")
lines.append("Implement the Vancomyzer Phase 1 website foundation.")
lines.append("")
lines.append("Primary goals:")
lines.append("- create a credible, clinician-readable website")
lines.append("- emphasize transparency, interpretability, and workflow usability")
lines.append("- support demo-first exploration before stronger conversion asks")
lines.append("- keep all copy evidence-aware and avoid unsupported claims")
lines.append("")

lines.append("## Pages to implement")
lines.append("")
lines.append("1. Homepage")
lines.append("2. About page")
lines.append("3. Trust & Evidence page")
lines.append("4. FAQ page")
lines.append("5. Contact / Institutional page")
lines.append("")

lines.append("## Required implementation inputs")
lines.append("")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_HANDOFF_PACKET.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_BUILD_SEQUENCE.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_ASSET_MANIFEST.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_SITEMAP_AND_NAVIGATION.md")
lines.append("- reports/page-specs/VANCOMYZER_HOMEPAGE_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_TRUST_EVIDENCE_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_FAQ_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_ABOUT_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_CONTACT_INSTITUTIONAL_IMPLEMENTATION_SPEC.md")
lines.append("")

lines.append("## Shared assets to finalize and reuse")
lines.append("")
lines.append("- one final homepage headline/subheadline set")
lines.append("- one final CTA set reused consistently")
lines.append("- one primary sample case")
lines.append("- one primary documentation/export example")
lines.append("- one FAQ shortlist for preview use")
lines.append("- trust/claims guardrails applied across all pages")
lines.append("")

lines.append("## Implementation requirements")
lines.append("")
lines.append("- keep navigation simple")
lines.append("- keep copy clinician-readable")
lines.append("- keep trust-building assets visible")
lines.append("- use demo-first exploration patterns")
lines.append("- avoid unsupported superiority, ROI, or validation claims")
lines.append("- reuse the strongest selected assets across pages")
lines.append("")

lines.append("## Suggested implementation order")
lines.append("")
lines.append("1. finalize shared assets")
lines.append("2. implement homepage")
lines.append("3. implement trust & evidence page")
lines.append("4. implement FAQ page")
lines.append("5. implement about page")
lines.append("6. implement contact / institutional page")
lines.append("7. perform consistency QA pass")
lines.append("")

lines.append("## Expected builder outputs")
lines.append("")
lines.append("- implemented page components/templates")
lines.append("- page copy inserted into build-ready files")
lines.append("- navigation and footer links wired")
lines.append("- cross-links between key Phase 1 pages")
lines.append("- consistent CTA usage")
lines.append("- notes on any missing inputs or implementation blockers")
lines.append("")

lines.append("## Handoff guardrails")
lines.append("")
lines.append("- do not expand scope beyond Phase 1 core pages")
lines.append("- do not invent unsupported product claims")
lines.append("- do not introduce unnecessary asset variety")
lines.append("- preserve trust, caution, and interpretability throughout")
lines.append("")

lines.append("## Copy-ready prompt")
lines.append("")
lines.append("Use the Vancomyzer Phase 1 handoff packet and related page specs to implement the five core Phase 1 website pages: homepage, about, trust & evidence, FAQ, and contact/institutional. Reuse the strongest selected case, export, FAQ, and CTA assets across pages. Keep the site clinician-readable, evidence-aware, transparency-focused, and demo-first. Flag any missing inputs before making assumptions.")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
