from pathlib import Path
from datetime import datetime

out = Path("reports/page-specs/VANCOMYZER_TRUST_EVIDENCE_IMPLEMENTATION_SPEC.md")

lines = []
lines.append("# Vancomyzer Trust and Evidence Page Implementation Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the trust and evidence page as a directly buildable Phase 1 page.")
lines.append("")

lines.append("## Page objective")
lines.append("Show clinicians and evaluators how Vancomyzer approaches transparency, interpretability, caution, and evidence-aware communication.")
lines.append("")

lines.append("## Section 1 — Page intro")
lines.append("")
lines.append("### Required elements")
lines.append("- page headline")
lines.append("- short purpose statement")
lines.append("- optional CTA to sample case or workflow")
lines.append("")
lines.append("### Content goals")
lines.append("- explain why trust and transparency matter")
lines.append("- keep the tone concrete and clinician-readable")
lines.append("- avoid sounding defensive or overly promotional")
lines.append("")

lines.append("## Section 2 — What users should be able to review")
lines.append("")
lines.append("### Required elements")
lines.append("- inputs used")
lines.append("- method/model used")
lines.append("- assumptions affecting output")
lines.append("- limitations and uncertainty")
lines.append("- caution/safety notes")
lines.append("")
lines.append("### Content goals")
lines.append("- make review expectations explicit")
lines.append("- show what a responsible user should inspect")
lines.append("- reinforce interpretability over black-box trust")
lines.append("")

lines.append("## Section 3 — Transparency principles")
lines.append("")
lines.append("### Required elements")
lines.append("- visible assumptions")
lines.append("- visible rationale")
lines.append("- visible limitations")
lines.append("- documentation-ready communication support")
lines.append("")
lines.append("### Content goals")
lines.append("- show the philosophy behind the product")
lines.append("- make transparency feel practical, not abstract")
lines.append("")

lines.append("## Section 4 — Evidence-aware communication")
lines.append("")
lines.append("### Required elements")
lines.append("- what the product is designed to support")
lines.append("- what the product should not imply")
lines.append("- caution around validation/superiority language")
lines.append("")
lines.append("### Content goals")
lines.append("- prevent overstatement")
lines.append("- keep claims aligned with actual product behavior")
lines.append("- reinforce clinical credibility")
lines.append("")

lines.append("## Section 5 — Practical examples")
lines.append("")
lines.append("### Required elements")
lines.append("- one case example")
lines.append("- one export/documentation example")
lines.append("- CTA to review more examples")
lines.append("")
lines.append("### Content goals")
lines.append("- make trust concrete through examples")
lines.append("- connect principles to real workflow")
lines.append("")

lines.append("## Section 6 — Final CTA")
lines.append("")
lines.append("### Required elements")
lines.append("- CTA to sample case, workflow, FAQ, or contact/evaluation")
lines.append("")
lines.append("### Content goals")
lines.append("- direct the user to a trust-building next step")
lines.append("- keep conversion soft and education-first")
lines.append("")

lines.append("## Recommended page CTAs")
lines.append("")
lines.append("- Review a sample case")
lines.append("- See how the workflow is explained")
lines.append("- Review a documentation-ready summary")
lines.append("- Contact us for evaluation")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- trust/evidence copy")
lines.append("- one selected case example")
lines.append("- one selected export example")
lines.append("- claim guardrails")
lines.append("- FAQ/supporting trust items")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- avoid unsupported validation claims")
lines.append("- avoid unsupported superiority claims")
lines.append("- keep language clinician-readable and concrete")
lines.append("- emphasize transparency, interpretability, and caution")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
