from pathlib import Path
from datetime import datetime

out = Path("reports/page-specs/VANCOMYZER_ABOUT_IMPLEMENTATION_SPEC.md")

lines = []
lines.append("# Vancomyzer About Page Implementation Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the about page as a directly buildable Phase 1 page.")
lines.append("")

lines.append("## Page objective")
lines.append("Explain why Vancomyzer exists, what philosophy guides it, and how its clinician-first design approach supports trust and interpretability.")
lines.append("")

lines.append("## Section 1 — Page intro")
lines.append("")
lines.append("### Required elements")
lines.append("- page headline")
lines.append("- short mission statement")
lines.append("- optional CTA to homepage, sample case, or trust/evidence page")
lines.append("")
lines.append("### Content goals")
lines.append("- explain Vancomyzer in concrete terms")
lines.append("- avoid vague brand language")
lines.append("- reinforce clinician-first positioning")
lines.append("")

lines.append("## Section 2 — Why Vancomyzer exists")
lines.append("")
lines.append("### Required elements")
lines.append("- workflow difficulty/problem statement")
lines.append("- need for transparency and interpretability")
lines.append("- rationale for clinician-readable outputs")
lines.append("")
lines.append("### Content goals")
lines.append("- make the mission practical and credible")
lines.append("- show the problem without exaggeration")
lines.append("- connect the mission to real workflow pain points")
lines.append("")

lines.append("## Section 3 — Product philosophy")
lines.append("")
lines.append("### Required elements")
lines.append("- transparency over black-box presentation")
lines.append("- interpretability over vague sophistication claims")
lines.append("- clinical caution over hype")
lines.append("- workflow usability over unnecessary complexity")
lines.append("")
lines.append("### Content goals")
lines.append("- clarify what principles shape the product")
lines.append("- keep each principle specific and relevant")
lines.append("- support trust and product differentiation")
lines.append("")

lines.append("## Section 4 — Who it is for")
lines.append("")
lines.append("### Required elements")
lines.append("- ICU pharmacists")
lines.append("- infectious disease pharmacists")
lines.append("- antimicrobial stewardship teams")
lines.append("- clinicians involved in vancomycin dosing review")
lines.append("")
lines.append("### Content goals")
lines.append("- define the intended audience clearly")
lines.append("- avoid overbroad positioning")
lines.append("- align page language with real users")
lines.append("")

lines.append("## Section 5 — How to explore the product")
lines.append("")
lines.append("### Required elements")
lines.append("- CTA to sample case")
lines.append("- CTA to workflow explanation")
lines.append("- CTA to documentation-ready example")
lines.append("- CTA to trust/evidence page")
lines.append("")
lines.append("### Content goals")
lines.append("- turn the about page into a useful entry point")
lines.append("- support soft exploration rather than hard selling")
lines.append("- reinforce education-first conversion")
lines.append("")

lines.append("## Recommended page CTAs")
lines.append("")
lines.append("- Review a sample case")
lines.append("- See how the workflow is explained")
lines.append("- Review a documentation-ready summary")
lines.append("- Explore the trust and evidence page")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- about-page copy")
lines.append("- trust/evidence copy")
lines.append("- one selected case example")
lines.append("- one selected export example")
lines.append("- homepage supporting language")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- avoid vague mission language")
lines.append("- avoid unsupported claims")
lines.append("- keep language clinician-readable and concrete")
lines.append("- emphasize transparency, interpretability, and workflow usability")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
