from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_PHASE1_ASSET_MANIFEST.md")

lines = []
lines.append("# Vancomyzer Phase 1 Asset Manifest")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Create a single implementation checklist for all assets needed to build Phase 1 pages.")
lines.append("")

lines.append("## Phase 1 pages")
lines.append("")
lines.append("1. Homepage")
lines.append("2. About page")
lines.append("3. Trust & Evidence page")
lines.append("4. FAQ page")
lines.append("5. Contact / Institutional page")
lines.append("")

lines.append("## Global reusable assets")
lines.append("")
lines.append("- homepage headline/subheadline")
lines.append("- trust and transparency highlights")
lines.append("- CTA set")
lines.append("- one primary sample case")
lines.append("- one primary documentation/export example")
lines.append("- supporting FAQ set")
lines.append("- evidence/claims guardrails")
lines.append("")

lines.append("## Homepage asset needs")
lines.append("")
lines.append("- homepage copy")
lines.append("- differentiator list")
lines.append("- trust highlights block")
lines.append("- selected case preview")
lines.append("- selected export preview")
lines.append("- FAQ preview items")
lines.append("- final CTA block")
lines.append("")

lines.append("## About page asset needs")
lines.append("")
lines.append("- mission statement")
lines.append("- product philosophy points")
lines.append("- intended audience list")
lines.append("- selected case/example links")
lines.append("- trust/evidence supporting links")
lines.append("")

lines.append("## Trust & Evidence page asset needs")
lines.append("")
lines.append("- trust/evidence core copy")
lines.append("- transparency principles")
lines.append("- evidence-aware claims language")
lines.append("- selected case example")
lines.append("- selected export example")
lines.append("- trust-supporting FAQ items")
lines.append("")

lines.append("## FAQ page asset needs")
lines.append("")
lines.append("- final FAQ question set")
lines.append("- grouped FAQ categories")
lines.append("- selected case/example links")
lines.append("- selected export/example links")
lines.append("- CTA block")
lines.append("")

lines.append("## Contact / Institutional page asset needs")
lines.append("")
lines.append("- evaluator-focused page copy")
lines.append("- team-value bullets")
lines.append("- selected evaluator-facing case example")
lines.append("- selected evaluator-facing export example")
lines.append("- evaluation CTA set")
lines.append("- supporting trust/evidence language")
lines.append("")

lines.append("## Asset source map")
lines.append("")
lines.append("- Homepage copy -> reports/website-copy/VANCOMYZER_HOMEPAGE_COPY.md")
lines.append("- About copy -> reports/about/VANCOMYZER_ABOUT_PAGE.md")
lines.append("- Trust/evidence copy -> reports/trust-evidence/VANCOMYZER_TRUST_AND_EVIDENCE.md")
lines.append("- FAQ copy -> reports/faq/VANCOMYZER_FAQ.md")
lines.append("- Contact/institutional copy -> reports/institutional/VANCOMYZER_CONTACT_AND_INSTITUTIONAL_PAGES.md")
lines.append("- Case library -> reports/case-library/VANCOMYZER_CASE_LIBRARY.md")
lines.append("- Export examples -> reports/documentation/examples/INDEX.md")
lines.append("- Claims guardrails -> tasks/063_validation_claims_guardrails.md")
lines.append("")

lines.append("## Implementation checklist")
lines.append("")
lines.append("- finalize page-level copy choices")
lines.append("- select one primary homepage case")
lines.append("- select one primary homepage export example")
lines.append("- select trust/evidence supporting assets")
lines.append("- finalize FAQ shortlist")
lines.append("- finalize evaluator-facing asset set")
lines.append("- apply claims guardrails across all pages")
lines.append("- verify CTA consistency across Phase 1")
lines.append("")

lines.append("## Guardrails")
lines.append("")
lines.append("- keep the asset set minimal for Phase 1")
lines.append("- reuse the same strongest examples across pages where appropriate")
lines.append("- avoid introducing content that is not yet supported by existing reports")
lines.append("- favor clarity and implementation speed over unnecessary variety")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
