from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_PHASE1_HANDOFF_PACKET.md")

lines = []
lines.append("# Vancomyzer Phase 1 Handoff Packet")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Bundle the key Phase 1 implementation documents into one handoff packet for direct build work.")
lines.append("")

lines.append("## Included implementation documents")
lines.append("")
lines.append("### Core planning")
lines.append("- reports/implementation/VANCOMYZER_IMPLEMENTATION_BLUEPRINT.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_SITEMAP_AND_NAVIGATION.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_ASSET_MANIFEST.md")
lines.append("- reports/implementation/VANCOMYZER_PHASE1_BUILD_SEQUENCE.md")
lines.append("")
lines.append("### MVP scope")
lines.append("- reports/mvp-spec/VANCOMYZER_MVP_WEBSITE_SPEC.md")
lines.append("")
lines.append("### Page implementation specs")
lines.append("- reports/page-specs/VANCOMYZER_HOMEPAGE_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_TRUST_EVIDENCE_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_FAQ_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_ABOUT_IMPLEMENTATION_SPEC.md")
lines.append("- reports/page-specs/VANCOMYZER_CONTACT_INSTITUTIONAL_IMPLEMENTATION_SPEC.md")
lines.append("")
lines.append("### Supporting content sources")
lines.append("- reports/website-copy/VANCOMYZER_HOMEPAGE_COPY.md")
lines.append("- reports/about/VANCOMYZER_ABOUT_PAGE.md")
lines.append("- reports/trust-evidence/VANCOMYZER_TRUST_AND_EVIDENCE.md")
lines.append("- reports/faq/VANCOMYZER_FAQ.md")
lines.append("- reports/institutional/VANCOMYZER_CONTACT_AND_INSTITUTIONAL_PAGES.md")
lines.append("- reports/case-library/VANCOMYZER_CASE_LIBRARY.md")
lines.append("- reports/documentation/examples/INDEX.md")
lines.append("")

lines.append("## Phase 1 build targets")
lines.append("")
lines.append("1. Homepage")
lines.append("2. About")
lines.append("3. Trust & Evidence")
lines.append("4. FAQ")
lines.append("5. Contact / Institutional")
lines.append("")

lines.append("## Shared assets to finalize before implementation")
lines.append("")
lines.append("- final homepage headline/subheadline")
lines.append("- final CTA set")
lines.append("- primary sample case")
lines.append("- primary documentation/export example")
lines.append("- final FAQ shortlist")
lines.append("- trust/claims guardrails")
lines.append("")

lines.append("## Recommended implementation order")
lines.append("")
lines.append("1. Finalize shared assets")
lines.append("2. Build homepage")
lines.append("3. Build trust & evidence page")
lines.append("4. Build FAQ page")
lines.append("5. Build about page")
lines.append("6. Build contact / institutional page")
lines.append("7. QA and consistency pass")
lines.append("")

lines.append("## Ready-to-build checklist")
lines.append("")
lines.append("- all 5 page specs exist")
lines.append("- sitemap/navigation exists")
lines.append("- asset manifest exists")
lines.append("- build sequence exists")
lines.append("- selected case/example/FAQ assets are finalized")
lines.append("- trust/claims guardrails are agreed")
lines.append("- CTA set is consistent across pages")
lines.append("")

lines.append("## Handoff guardrails")
lines.append("")
lines.append("- keep Phase 1 scope tight")
lines.append("- reuse the same strongest examples across pages")
lines.append("- prefer clarity and trust over feature sprawl")
lines.append("- keep all copy clinician-readable and evidence-aware")
lines.append("- do not introduce unsupported claims during implementation")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
