from pathlib import Path
from datetime import datetime

out = Path("reports/page-specs/VANCOMYZER_FAQ_IMPLEMENTATION_SPEC.md")

lines = []
lines.append("# Vancomyzer FAQ Page Implementation Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the FAQ page as a directly buildable Phase 1 page.")
lines.append("")

lines.append("## Page objective")
lines.append("Answer first-order clinician questions clearly, reduce confusion, and reinforce trust in Vancomyzer's transparent workflow.")
lines.append("")

lines.append("## Section 1 — Page intro")
lines.append("")
lines.append("### Required elements")
lines.append("- page headline")
lines.append("- short purpose statement")
lines.append("- optional CTA to workflow, case, or trust/evidence page")
lines.append("")
lines.append("### Content goals")
lines.append("- explain why the FAQ exists")
lines.append("- keep tone clear, practical, and clinician-readable")
lines.append("- support trust and onboarding")
lines.append("")

lines.append("## Section 2 — Core dosing workflow questions")
lines.append("")
lines.append("### Required elements")
lines.append("- AUC-guided dosing question")
lines.append("- Bayesian vs traditional PK question")
lines.append("- trough vs AUC question")
lines.append("")
lines.append("### Content goals")
lines.append("- address the most important workflow concepts")
lines.append("- keep answers educational and concise")
lines.append("- avoid unnecessary jargon")
lines.append("")

lines.append("## Section 3 — Transparency and trust questions")
lines.append("")
lines.append("### Required elements")
lines.append("- why transparency matters")
lines.append("- what users should review before accepting a recommendation")
lines.append("- why assumptions and limitations should be visible")
lines.append("")
lines.append("### Content goals")
lines.append("- reinforce trust-building principles")
lines.append("- show what responsible review looks like")
lines.append("- connect FAQ content to the trust/evidence page")
lines.append("")

lines.append("## Section 4 — Workflow and documentation questions")
lines.append("")
lines.append("### Required elements")
lines.append("- documentation-ready summaries question")
lines.append("- case examples question")
lines.append("- workflow interpretation question")
lines.append("")
lines.append("### Content goals")
lines.append("- show practical day-to-day value")
lines.append("- connect answers to sample exports and cases")
lines.append("- keep examples concrete")
lines.append("")

lines.append("## Section 5 — CTA block")
lines.append("")
lines.append("### Required elements")
lines.append("- CTA to sample case")
lines.append("- CTA to workflow page")
lines.append("- CTA to documentation-ready example")
lines.append("")
lines.append("### Content goals")
lines.append("- give users a useful next step")
lines.append("- move from explanation to exploration")
lines.append("")

lines.append("## Recommended page CTAs")
lines.append("")
lines.append("- Review a sample case")
lines.append("- See how the workflow is explained")
lines.append("- Review a documentation-ready summary")
lines.append("- Explore the trust and evidence page")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- FAQ copy")
lines.append("- trust/evidence copy")
lines.append("- one sample case")
lines.append("- one documentation/export example")
lines.append("- homepage/about supporting language")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- keep answers concise and clinician-readable")
lines.append("- avoid unsupported claims")
lines.append("- keep language educational and practical")
lines.append("- reinforce transparency, interpretability, and caution")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
