from pathlib import Path
from datetime import datetime

out = Path("reports/mvp-spec/VANCOMYZER_MVP_WEBSITE_SPEC.md")

lines = []
lines.append("# Vancomyzer MVP Website Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the minimum viable website build for Vancomyzer Phase 1.")
lines.append("")

lines.append("## Phase 1 objective")
lines.append("Create a credible, trust-building website that explains what Vancomyzer is, why it matters, and how a first-time visitor should explore it.")
lines.append("")

lines.append("## Required MVP pages")
lines.append("")
lines.append("### 1. Homepage")
lines.append("- hero headline and subheadline")
lines.append("- positioning summary")
lines.append("- trust/transparency highlights")
lines.append("- sample case preview")
lines.append("- CTA to explore workflow or review a case")
lines.append("")

lines.append("### 2. About page")
lines.append("- mission")
lines.append("- product philosophy")
lines.append("- clinician-first design principles")
lines.append("- who it is for")
lines.append("")

lines.append("### 3. Trust and evidence page")
lines.append("- transparency principles")
lines.append("- what users should review")
lines.append("- limitations/caution framing")
lines.append("- evidence-aware messaging")
lines.append("")

lines.append("### 4. FAQ page")
lines.append("- core Bayesian/AUC questions")
lines.append("- transparency and workflow questions")
lines.append("- documentation and interpretation questions")
lines.append("")

lines.append("### 5. Contact / institutional page")
lines.append("- who should contact")
lines.append("- what evaluators can review")
lines.append("- demo-first CTA path")
lines.append("- evaluation/contact CTA")
lines.append("")

lines.append("## Recommended MVP reusable sections")
lines.append("")
lines.append("- hero section")
lines.append("- trust highlights block")
lines.append("- case preview block")
lines.append("- CTA block")
lines.append("- FAQ preview block")
lines.append("- documentation/export preview block")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- homepage copy")
lines.append("- about-page copy")
lines.append("- trust/evidence copy")
lines.append("- FAQ copy")
lines.append("- sample case summaries")
lines.append("- sample export examples")
lines.append("")

lines.append("## What can wait until later phases")
lines.append("")
lines.append("- full resource hub")
lines.append("- full SEO page set")
lines.append("- comparison pages")
lines.append("- newsletter infrastructure")
lines.append("- webinar/event program")
lines.append("- outreach and demo deck expansion")
lines.append("")

lines.append("## MVP success criteria")
lines.append("")
lines.append("- a first-time visitor understands what Vancomyzer is")
lines.append("- trust and caution are visible")
lines.append("- the site offers a clear next step")
lines.append("- the site has at least one strong demo/case path")
lines.append("- messaging stays concrete and evidence-aware")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- avoid unsupported claims")
lines.append("- keep language clinician-readable")
lines.append("- emphasize transparency, interpretability, and workflow usability")
lines.append("- do not overstate validation or superiority")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
