from pathlib import Path
from datetime import datetime

out = Path("reports/page-specs/VANCOMYZER_HOMEPAGE_IMPLEMENTATION_SPEC.md")

lines = []
lines.append("# Vancomyzer Homepage Implementation Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the homepage as a directly buildable Phase 1 page.")
lines.append("")

lines.append("## Homepage objective")
lines.append("Help a first-time visitor quickly understand what Vancomyzer is, why it matters, and what to do next.")
lines.append("")

lines.append("## Section 1 — Hero")
lines.append("")
lines.append("### Required elements")
lines.append("- headline")
lines.append("- subheadline")
lines.append("- primary CTA")
lines.append("- optional secondary CTA")
lines.append("")
lines.append("### Content goals")
lines.append("- explain Vancomyzer in plain clinician-readable language")
lines.append("- emphasize transparency, interpretability, and workflow usability")
lines.append("- avoid vague or hype-heavy positioning")
lines.append("")

lines.append("## Section 2 — Why Vancomyzer")
lines.append("")
lines.append("### Required elements")
lines.append("- short positioning summary")
lines.append("- 3 to 5 key differentiators")
lines.append("")
lines.append("### Content goals")
lines.append("- clarify what makes the product different")
lines.append("- highlight transparency and clinician-readable outputs")
lines.append("- keep claims evidence-aware")
lines.append("")

lines.append("## Section 3 — Trust and transparency highlights")
lines.append("")
lines.append("### Required elements")
lines.append("- visible assumptions highlight")
lines.append("- visible method/model highlight")
lines.append("- caution/limitations highlight")
lines.append("- documentation-ready summary highlight")
lines.append("")
lines.append("### Content goals")
lines.append("- build trust before stronger conversion asks")
lines.append("- show how the product avoids black-box perception")
lines.append("")

lines.append("## Section 4 — Sample case preview")
lines.append("")
lines.append("### Required elements")
lines.append("- one strong case preview")
lines.append("- short educational summary")
lines.append("- CTA to review case")
lines.append("")
lines.append("### Content goals")
lines.append("- make the workflow concrete")
lines.append("- show how interpretation and assumptions are presented")
lines.append("- support demo-first exploration")
lines.append("")

lines.append("## Section 5 — Documentation/export preview")
lines.append("")
lines.append("### Required elements")
lines.append("- quick summary example")
lines.append("- clinical note style example")
lines.append("- CTA to review documentation-ready output")
lines.append("")
lines.append("### Content goals")
lines.append("- show practical workflow value")
lines.append("- reinforce communication/documentation support")
lines.append("")

lines.append("## Section 6 — FAQ preview")
lines.append("")
lines.append("### Required elements")
lines.append("- 3 to 5 short FAQ items")
lines.append("- CTA to full FAQ page")
lines.append("")
lines.append("### Content goals")
lines.append("- address first-order objections and confusion")
lines.append("- reinforce trust and clarity")
lines.append("")

lines.append("## Section 7 — Final CTA")
lines.append("")
lines.append("### Required elements")
lines.append("- primary CTA")
lines.append("- optional secondary CTA")
lines.append("")
lines.append("### Content goals")
lines.append("- direct the user to a meaningful next step")
lines.append("- prefer demo-first exploration over hard selling")
lines.append("")

lines.append("## Recommended homepage CTAs")
lines.append("")
lines.append("- Explore the workflow")
lines.append("- Review a sample case")
lines.append("- See how calculations are explained")
lines.append("- Review a documentation-ready summary")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- homepage copy")
lines.append("- one selected demo case")
lines.append("- one selected export example")
lines.append("- trust/evidence messaging")
lines.append("- FAQ preview items")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- avoid unsupported claims")
lines.append("- keep language clinician-readable")
lines.append("- emphasize transparency, interpretability, and workflow usability")
lines.append("- do not overstate validation or superiority")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
