from pathlib import Path
from datetime import datetime

dashboard = Path("reports/market-intel/weekly/COMBINED_INTEL_DASHBOARD.md")
out = Path("reports/executive/EXECUTIVE_SUMMARY.md")

dashboard_text = dashboard.read_text(encoding="utf-8") if dashboard.exists() else "(missing combined dashboard)"

lines = []
lines.append("# Vancomyzer Executive Summary")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")
lines.append("## Overall status")
lines.append("")
lines.append("- Intelligence pipeline is operational.")
lines.append("- PubMed monitor is working.")
lines.append("- Google News RSS monitor is working.")
lines.append("- Guideline monitor is partially working (IDSA and FDA OK; ASHP direct fetch blocked).")
lines.append("- Reddit direct scraping is blocked without API access.")
lines.append("")
lines.append("## Most important signals")
lines.append("")
lines.append("- Bayesian dosing, AUC monitoring, and precision dosing remain central themes.")
lines.append("- Product differentiation should emphasize transparent calculations and workflow usability.")
lines.append("- Marketing should focus on implementation pain points and practical clinician education.")
lines.append("")
lines.append("## Highest-priority product opportunities")
lines.append("")
lines.append("- Improve explanation of Bayesian/AUC logic.")
lines.append("- Reduce dosing workflow friction.")
lines.append("- Make results more interpretable and auditable.")
lines.append("")
lines.append("## Highest-priority marketing opportunities")
lines.append("")
lines.append("- Build educational content on Bayesian dosing and AUC monitoring.")
lines.append("- Create SEO-focused pages around vancomycin dosing workflow problems.")
lines.append("- Position Vancomyzer around clarity, speed, and trust.")
lines.append("")
lines.append("## Immediate next actions")
lines.append("")
lines.append("- Populate competitor baseline reports for VancoCalc, DoseMeRx, InsightRx, and PrecisePK.")
lines.append("- Add ASHP fallback monitoring method.")
lines.append("- Turn repeated signals into product and content roadmap items.")
lines.append("")
lines.append("## Source reference")
lines.append("")
lines.append("Primary input:")
lines.append("- reports/market-intel/weekly/COMBINED_INTEL_DASHBOARD.md")
lines.append("")
lines.append("## Dashboard snapshot")
lines.append("")
lines.append("```")
lines.append(dashboard_text[:4000])
lines.append("```")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}")
