from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_IMPLEMENTATION_BLUEPRINT.md")

lines = []
lines.append("# Vancomyzer Implementation Blueprint")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Organize Vancomyzer website, content, trust, SEO, and conversion work into a build-ready implementation plan.")
lines.append("")

lines.append("## Phase 1 — Core site foundation")
lines.append("")
lines.append("### Priority pages")
lines.append("- Homepage")
lines.append("- About page")
lines.append("- Trust and evidence page")
lines.append("- FAQ page")
lines.append("- Contact / institutional page")
lines.append("")
lines.append("### Core objectives")
lines.append("- establish clear positioning")
lines.append("- build trust through transparency")
lines.append("- give first-time visitors a simple path to explore")
lines.append("")

lines.append("## Phase 2 — Product and workflow pages")
lines.append("")
lines.append("### Priority pages")
lines.append("- Transparency feature page")
lines.append("- Bayesian/AUC workflow page")
lines.append("- Documentation export page")
lines.append("- Onboarding flow page")
lines.append("")
lines.append("### Core objectives")
lines.append("- explain how Vancomyzer works")
lines.append("- make workflow value concrete")
lines.append("- reinforce interpretability and documentation support")
lines.append("")

lines.append("## Phase 3 — Educational growth pages")
lines.append("")
lines.append("### Priority pages")
lines.append("- SEO landing pages")
lines.append("- Comparison pages")
lines.append("- Case pages")
lines.append("- Resource hub")
lines.append("")
lines.append("### Core objectives")
lines.append("- capture search intent")
lines.append("- convert education into trust")
lines.append("- connect visitors to deeper content and demos")
lines.append("")

lines.append("## Phase 4 — Conversion assets")
lines.append("")
lines.append("### Priority assets")
lines.append("- Lead magnets")
lines.append("- Newsletter / digest")
lines.append("- Demo-first conversion flow")
lines.append("- Pricing / conversion page")
lines.append("")
lines.append("### Core objectives")
lines.append("- convert educational interest into repeat engagement")
lines.append("- use demo-first trust building before stronger CTAs")
lines.append("- keep capture and conversion low-friction")
lines.append("")

lines.append("## Phase 5 — Institutional and evaluator assets")
lines.append("")
lines.append("### Priority assets")
lines.append("- Demo deck")
lines.append("- Outreach assets")
lines.append("- Webinar/event program")
lines.append("- Institutional evaluation flow")
lines.append("")
lines.append("### Core objectives")
lines.append("- support serious evaluators")
lines.append("- provide reusable outreach and presentation assets")
lines.append("- align institutional messaging with trust and caution")
lines.append("")

lines.append("## Recommended build order")
lines.append("")
lines.append("1. Homepage + trust/evidence + FAQ")
lines.append("2. Transparency/Bayesian/AUC feature pages")
lines.append("3. Case pages + sample exports")
lines.append("4. SEO and comparison pages")
lines.append("5. Resource hub + onboarding flow")
lines.append("6. Lead magnets + newsletter + social repurposing")
lines.append("7. Institutional pages + demo deck + outreach")
lines.append("")

lines.append("## Implementation dependencies")
lines.append("")
lines.append("- Positioning and messaging should be finalized before homepage implementation")
lines.append("- UI transparency spec should inform product/workflow pages")
lines.append("- Case library and sample exports should inform demo, onboarding, and case pages")
lines.append("- Trust/evidence guardrails should be applied across all public-facing copy")
lines.append("- SEO and resource-hub structure should align with onboarding and conversion flow")
lines.append("")

lines.append("## Guardrails")
lines.append("")
lines.append("- avoid unsupported claims")
lines.append("- keep language clinician-readable")
lines.append("- prefer trust, clarity, and interpretability over hype")
lines.append("- keep educational value visible in every phase")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
