from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_PHASE1_BUILD_SEQUENCE.md")

lines = []
lines.append("# Vancomyzer Phase 1 Build Sequence")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the concrete order for implementing Phase 1 pages and shared assets.")
lines.append("")

lines.append("## Build philosophy")
lines.append("- build shared assets first")
lines.append("- build the homepage first because it sets overall messaging")
lines.append("- build trust-supporting pages early")
lines.append("- reuse the same strongest examples across pages")
lines.append("- keep scope tight and implementation practical")
lines.append("")

lines.append("## Step 1 — Finalize shared assets")
lines.append("")
lines.append("### Required outputs")
lines.append("- final homepage headline/subheadline")
lines.append("- final CTA set")
lines.append("- one primary sample case")
lines.append("- one primary documentation/export example")
lines.append("- FAQ shortlist")
lines.append("- claims/trust guardrails")
lines.append("")
lines.append("### Why first")
lines.append("- these assets are reused across multiple pages")
lines.append("- finalizing them early reduces later rework")
lines.append("")

lines.append("## Step 2 — Build homepage")
lines.append("")
lines.append("### Required inputs")
lines.append("- homepage implementation spec")
lines.append("- selected homepage assets")
lines.append("")
lines.append("### Why second")
lines.append("- homepage is the main entry point")
lines.append("- it establishes trust, positioning, and first-visit flow")
lines.append("")

lines.append("## Step 3 — Build trust & evidence page")
lines.append("")
lines.append("### Required inputs")
lines.append("- trust/evidence implementation spec")
lines.append("- selected trust-supporting assets")
lines.append("")
lines.append("### Why third")
lines.append("- trust is a core differentiator")
lines.append("- this page supports both homepage and evaluator flow")
lines.append("")

lines.append("## Step 4 — Build FAQ page")
lines.append("")
lines.append("### Required inputs")
lines.append("- FAQ implementation spec")
lines.append("- final FAQ shortlist")
lines.append("- supporting case/export links")
lines.append("")
lines.append("### Why fourth")
lines.append("- FAQ reduces first-order confusion and supports onboarding")
lines.append("")

lines.append("## Step 5 — Build about page")
lines.append("")
lines.append("### Required inputs")
lines.append("- about implementation spec")
lines.append("- finalized mission/philosophy copy")
lines.append("")
lines.append("### Why fifth")
lines.append("- about page reinforces mission and philosophy after core trust pages exist")
lines.append("")

lines.append("## Step 6 — Build contact / institutional page")
lines.append("")
lines.append("### Required inputs")
lines.append("- contact/institutional implementation spec")
lines.append("- evaluator-facing case/export examples")
lines.append("- final CTA sequence")
lines.append("")
lines.append("### Why sixth")
lines.append("- this page depends on trust, examples, and core messaging already being defined")
lines.append("")

lines.append("## Step 7 — QA and consistency pass")
lines.append("")
lines.append("### Required checks")
lines.append("- CTA consistency across all pages")
lines.append("- trust/evidence language consistency")
lines.append("- reuse of selected case/export assets")
lines.append("- claims guardrails applied everywhere")
lines.append("- cross-links implemented correctly")
lines.append("")

lines.append("## Deliverable checklist")
lines.append("")
lines.append("- shared asset bundle finalized")
lines.append("- 5 Phase 1 pages implemented")
lines.append("- navigation and cross-links aligned")
lines.append("- trust/caution language reviewed")
lines.append("- demo-first exploration path preserved")
lines.append("")

lines.append("## Guardrails")
lines.append("")
lines.append("- do not expand scope before the 5 core pages are coherent")
lines.append("- do not introduce new examples unless current selected examples fail")
lines.append("- prefer consistency over variety")
lines.append("- keep wording concrete, cautious, and clinician-readable")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
