from pathlib import Path
from datetime import datetime

out = Path("reports/implementation/VANCOMYZER_PHASE1_SITEMAP_AND_NAVIGATION.md")

lines = []
lines.append("# Vancomyzer Phase 1 Site Map and Navigation")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the Phase 1 page set as a coherent site structure with clear visitor navigation.")
lines.append("")

lines.append("## Phase 1 pages")
lines.append("")
lines.append("1. Homepage")
lines.append("2. About page")
lines.append("3. Trust and evidence page")
lines.append("4. FAQ page")
lines.append("5. Contact / institutional page")
lines.append("")

lines.append("## Recommended primary navigation")
lines.append("")
lines.append("- Home")
lines.append("- How it works")
lines.append("- Trust & Evidence")
lines.append("- FAQ")
lines.append("- About")
lines.append("- Contact")
lines.append("")

lines.append("## Navigation notes")
lines.append("")
lines.append("- 'How it works' can initially route to homepage sections or a workflow-focused anchor section")
lines.append("- Trust & Evidence should be top-level because trust is a core differentiator")
lines.append("- FAQ should be directly accessible for first-order objections and education")
lines.append("- About should reinforce mission and philosophy without becoming a dead-end page")
lines.append("- Contact should support both demo-first exploration and evaluator inquiry")
lines.append("")

lines.append("## Recommended footer navigation")
lines.append("")
lines.append("- About")
lines.append("- Trust & Evidence")
lines.append("- FAQ")
lines.append("- Contact")
lines.append("- Sample case")
lines.append("- Documentation example")
lines.append("")

lines.append("## Cross-linking recommendations")
lines.append("")
lines.append("### Homepage should link to:")
lines.append("- sample case")
lines.append("- trust & evidence")
lines.append("- documentation example")
lines.append("- FAQ")
lines.append("")
lines.append("### About page should link to:")
lines.append("- homepage")
lines.append("- trust & evidence")
lines.append("- sample case")
lines.append("- documentation example")
lines.append("")
lines.append("### Trust & Evidence page should link to:")
lines.append("- sample case")
lines.append("- documentation example")
lines.append("- FAQ")
lines.append("- contact/institutional")
lines.append("")
lines.append("### FAQ page should link to:")
lines.append("- trust & evidence")
lines.append("- workflow explanation")
lines.append("- sample case")
lines.append("- documentation example")
lines.append("")
lines.append("### Contact / Institutional page should link to:")
lines.append("- sample case")
lines.append("- trust & evidence")
lines.append("- documentation example")
lines.append("- contact CTA / evaluation CTA")
lines.append("")

lines.append("## Recommended first-visit path")
lines.append("")
lines.append("1. Homepage")
lines.append("2. Trust & Evidence or sample case")
lines.append("3. FAQ or documentation example")
lines.append("4. Contact / evaluation path")
lines.append("")

lines.append("## Guardrails")
lines.append("")
lines.append("- Keep top navigation simple")
lines.append("- Avoid overwhelming users with too many Phase 1 links")
lines.append("- Prioritize trust-building paths over hard-selling paths")
lines.append("- Make educational next steps visible on every page")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
