from pathlib import Path
from datetime import datetime

out = Path("reports/page-specs/VANCOMYZER_CONTACT_INSTITUTIONAL_IMPLEMENTATION_SPEC.md")

lines = []
lines.append("# Vancomyzer Contact / Institutional Page Implementation Spec")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Purpose")
lines.append("Define the contact / institutional page as a directly buildable Phase 1 page.")
lines.append("")

lines.append("## Page objective")
lines.append("Help serious evaluators, stewardship teams, and clinician leaders understand whether Vancomyzer is worth exploring further and what they should review first.")
lines.append("")

lines.append("## Section 1 — Page intro")
lines.append("")
lines.append("### Required elements")
lines.append("- page headline")
lines.append("- short evaluator-focused summary")
lines.append("- primary CTA")
lines.append("- optional secondary CTA")
lines.append("")
lines.append("### Content goals")
lines.append("- clarify who this page is for")
lines.append("- keep tone credible and concrete")
lines.append("- avoid generic enterprise language")
lines.append("")

lines.append("## Section 2 — Who this is for")
lines.append("")
lines.append("### Required elements")
lines.append("- antimicrobial stewardship teams")
lines.append("- ICU and ID pharmacists")
lines.append("- clinicians involved in vancomycin dosing review")
lines.append("- clinical leaders evaluating workflow tools")
lines.append("")
lines.append("### Content goals")
lines.append("- define the intended institutional/evaluator audience")
lines.append("- avoid overbroad positioning")
lines.append("- align page language with actual users")
lines.append("")

lines.append("## Section 3 — Why teams may care")
lines.append("")
lines.append("### Required elements")
lines.append("- workflow clarity")
lines.append("- interpretability of outputs")
lines.append("- documentation-ready summaries")
lines.append("- visible assumptions and limitations")
lines.append("")
lines.append("### Content goals")
lines.append("- explain practical team value")
lines.append("- keep value grounded and evidence-aware")
lines.append("- avoid unsupported ROI or outcome claims")
lines.append("")

lines.append("## Section 4 — What evaluators should review")
lines.append("")
lines.append("### Required elements")
lines.append("- sample case")
lines.append("- workflow explanation")
lines.append("- documentation/export example")
lines.append("- trust/evidence page")
lines.append("")
lines.append("### Content goals")
lines.append("- make evaluation steps obvious")
lines.append("- support demo-first exploration")
lines.append("- reduce friction before contact")
lines.append("")

lines.append("## Section 5 — Contact / evaluation CTA block")
lines.append("")
lines.append("### Required elements")
lines.append("- request workflow evaluation CTA")
lines.append("- contact CTA")
lines.append("- optional demo-first CTA")
lines.append("")
lines.append("### Content goals")
lines.append("- keep conversion soft and credible")
lines.append("- support both exploration and direct inquiry")
lines.append("- avoid aggressive sales posture")
lines.append("")

lines.append("## Recommended page CTAs")
lines.append("")
lines.append("- Request a workflow evaluation")
lines.append("- Review a sample case")
lines.append("- See a documentation-ready summary")
lines.append("- Contact us")
lines.append("")

lines.append("## Required supporting assets")
lines.append("")
lines.append("- institutional/contact page copy")
lines.append("- one selected case example")
lines.append("- one selected export example")
lines.append("- trust/evidence supporting language")
lines.append("- homepage/about supporting language")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- avoid unsupported ROI claims")
lines.append("- avoid unsupported validation or superiority claims")
lines.append("- keep language clinician-readable and concrete")
lines.append("- emphasize transparency, interpretability, and workflow support")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
