from pathlib import Path
from datetime import datetime

dashboard = Path("reports/market-intel/weekly/COMBINED_INTEL_DASHBOARD.md")
executive = Path("reports/executive/EXECUTIVE_SUMMARY.md")
competitors = Path("reports/competitive-intel/COMPETITOR_FIRST_PASS.md")
out = Path("reports/roadmap/VANCOMYZER_ACTION_ROADMAP.md")

def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else f"(missing: {path})"

dashboard_text = read(dashboard)
executive_text = read(executive)
competitor_text = read(competitors)

lines = []
lines.append("# Vancomyzer Action Roadmap")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")
lines.append("## Decision inputs")
lines.append("")
lines.append(f"- Combined dashboard present: {'yes' if dashboard.exists() else 'no'}")
lines.append(f"- Executive summary present: {'yes' if executive.exists() else 'no'}")
lines.append(f"- Competitor first-pass present: {'yes' if competitors.exists() else 'no'}")
lines.append("")
lines.append("## Priority 1 — Product trust and clarity")
lines.append("")
lines.append("1. Improve explanation of Bayesian/AUC logic in the UI.")
lines.append("2. Make outputs more transparent, auditable, and clinician-readable.")
lines.append("3. Surface assumptions, units, and key calculations more explicitly.")
lines.append("")
lines.append("Why:")
lines.append("- Current market signals emphasize Bayesian dosing, AUC, and precision workflow.")
lines.append("- Competitor pages heavily market Bayesian precision, but often with enterprise-style abstraction.")
lines.append("- Vancomyzer can differentiate through clarity and transparency.")
lines.append("")
lines.append("## Priority 2 — Workflow usability")
lines.append("")
lines.append("1. Reduce friction in patient data entry and recalculation flow.")
lines.append("2. Improve interpretation of dose recommendations and graphs.")
lines.append("3. Build trust-oriented UX around why a recommendation changed.")
lines.append("")
lines.append("Why:")
lines.append("- Public signals suggest implementation friction is a core pain point.")
lines.append("- Workflow usability is a clear adoption lever.")
lines.append("")
lines.append("## Priority 3 — Content and acquisition")
lines.append("")
lines.append("1. Create educational pages on Bayesian dosing, AUC monitoring, and workflow pitfalls.")
lines.append("2. Build SEO pages around vancomycin dosing pain points.")
lines.append("3. Use educational trust-building content before direct promotion.")
lines.append("")
lines.append("Why:")
lines.append("- Research and competitor signals both support education-led positioning.")
lines.append("- This is likely the fastest near-term marketing path.")
lines.append("")
lines.append("## Priority 4 — Competitive differentiation")
lines.append("")
lines.append("1. Position Vancomyzer as transparent and clinician-friendly.")
lines.append("2. Emphasize explainability, not just precision.")
lines.append("3. Identify where competitors appear heavy, enterprise-first, or less transparent.")
lines.append("")
lines.append("## Suggested next build sequence")
lines.append("")
lines.append("1. PK/UI transparency improvements")
lines.append("2. Dosing workflow simplification")
lines.append("3. Content roadmap and landing page upgrades")
lines.append("4. Competitor-specific positioning matrix")
lines.append("5. Broader monitoring coverage")
lines.append("")
lines.append("## Snapshot excerpts")
lines.append("")
lines.append("### Executive summary excerpt")
lines.append("```")
lines.append(executive_text[:1800])
lines.append("```")
lines.append("")
lines.append("### Competitor excerpt")
lines.append("```")
lines.append(competitor_text[:1800])
lines.append("```")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}")
