from pathlib import Path
from datetime import datetime

out = Path("reports/execution/VANCOMYZER_EXECUTION_NOTE_SYSTEM.md")

lines = []
lines.append("# Vancomyzer Execution Note System")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")
lines.append("## Purpose")
lines.append("Define a standard execution-note format so every task result is reviewable and traceable.")
lines.append("")
lines.append("## Required fields")
lines.append("- task metadata")
lines.append("- inputs reviewed")
lines.append("- summary of work performed")
lines.append("- key decisions")
lines.append("- output produced")
lines.append("- risks / blockers")
lines.append("- recommended next step")
lines.append("- review notes")
lines.append("- status recommendation")
lines.append("")
lines.append("## Status recommendation rules")
lines.append("- review_ready: work completed and ready for review")
lines.append("- blocked: task cannot proceed without additional input")
lines.append("- done: task completed and accepted")
lines.append("")
lines.append("## Guardrails")
lines.append("- every assigned task should produce an execution note")
lines.append("- notes should be concise but specific")
lines.append("- blockers must be explicit")
lines.append("- status changes should match the note content")
lines.append("")
lines.append("## File location pattern")
lines.append("- reports/execution/notes/<task_file_stem>_execution_note.md")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {out}")
