from pathlib import Path
from datetime import datetime

out = Path("reports/website-copy/VANCOMYZER_HOMEPAGE_COPY.md")

lines = []
lines.append("# Vancomyzer Homepage Copy")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Hero headline variants")
lines.append("")
lines.append("1. Vancomycin dosing with more clarity")
lines.append("2. Transparent Bayesian dosing for clinical workflow")
lines.append("3. AUC-guided dosing you can understand and trust")
lines.append("4. Explainable vancomycin dosing for real clinical use")
lines.append("5. Precision dosing with clearer clinical reasoning")
lines.append("")

lines.append("## Hero subheadline variants")
lines.append("")
lines.append("1. Review recommendations, assumptions, and outputs in a more clinician-readable workflow.")
lines.append("2. Make vancomycin dosing easier to interpret with transparent logic and clearer outputs.")
lines.append("3. Support clinical review with explainable dosing summaries and documentation-ready exports.")
lines.append("4. Understand why a recommendation was made, what assumptions were used, and what cautions matter.")
lines.append("")

lines.append("## Primary CTA variants")
lines.append("")
lines.append("- Explore the workflow")
lines.append("- Review a sample case")
lines.append("- See how calculations are explained")
lines.append("- View a documentation-ready summary")
lines.append("")

lines.append("## Section: Why Vancomyzer")
lines.append("")
lines.append("Vancomyzer is designed to make vancomycin dosing easier to review, explain, and trust. Instead of hiding assumptions behind a black box, it aims to present recommendations with clearer logic, interpretable outputs, and workflow-friendly summaries.")
lines.append("")

lines.append("## Section: What makes it different")
lines.append("")
lines.append("- Transparent calculation logic")
lines.append("- Clinician-readable outputs")
lines.append("- Explainable Bayesian/AUC workflow")
lines.append("- Documentation-ready summaries")
lines.append("- Trust-oriented presentation of assumptions and limitations")
lines.append("")

lines.append("## Section: Sample case previews")
lines.append("")
lines.append("### Stable routine monitoring")
lines.append("Review a straightforward case with preserved renal function and routine AUC-guided dosing interpretation.")
lines.append("")
lines.append("### Renal instability and caution")
lines.append("See how changing renal function affects interpretation, assumptions, and caution notes.")
lines.append("")
lines.append("### Sparse data and visible assumptions")
lines.append("Understand how limited level information changes confidence and why visible assumptions matter.")
lines.append("")
lines.append("### AUC versus trough interpretation")
lines.append("Compare why an AUC-guided interpretation may differ from trough-based reasoning.")
lines.append("")

lines.append("## Section: Export and documentation preview")
lines.append("")
lines.append("Generate quick summaries, clinical-note style outputs, and educational case explanations that are easier to review and share in workflow.")
lines.append("")

lines.append("## Section: Trust and transparency")
lines.append("")
lines.append("Vancomyzer should emphasize what inputs were used, what method was applied, what assumptions affected the result, and where caution is warranted. The goal is not only precision, but interpretability.")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- Do not claim superiority without evidence")
lines.append("- Do not imply validated clinical outcome advantage without support")
lines.append("- Keep copy aligned with actual product behavior")
lines.append("- Prefer clarity and credibility over hype")
lines.append("")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}")
