from pathlib import Path
from datetime import datetime

out = Path("reports/feature-pages/VANCOMYZER_FEATURE_PAGES.md")

lines = []

lines.append("# Vancomyzer Feature Page Copy")
lines.append("")
lines.append(f"Generated: {datetime.utcnow().isoformat()}Z")
lines.append("")

lines.append("## Feature Page: Transparency")
lines.append("")
lines.append("### Headline")
lines.append("Transparent vancomycin dosing calculations")
lines.append("")
lines.append("### Subheadline")
lines.append("Review assumptions, inputs, and outputs with clearer reasoning rather than hidden black-box logic.")
lines.append("")
lines.append("### Key points")
lines.append("- Visible calculation assumptions")
lines.append("- Clear reasoning behind recommendations")
lines.append("- Interpretable exposure estimates")
lines.append("- Clinician-readable explanation of outputs")
lines.append("")

lines.append("## Feature Page: Bayesian and AUC workflow")
lines.append("")
lines.append("### Headline")
lines.append("Explainable Bayesian and AUC-guided dosing")
lines.append("")
lines.append("### Subheadline")
lines.append("Understand how exposure estimates and recommendations are derived, with visible assumptions and workflow-friendly summaries.")
lines.append("")
lines.append("### Key points")
lines.append("- Bayesian dosing interpretation")
lines.append("- AUC-guided monitoring")
lines.append("- Interpretable exposure estimates")
lines.append("- Transparent workflow logic")
lines.append("")

lines.append("## Feature Page: Documentation exports")
lines.append("")
lines.append("### Headline")
lines.append("Documentation-ready dosing summaries")
lines.append("")
lines.append("### Subheadline")
lines.append("Generate clinician-readable summaries that support review, communication, and documentation workflows.")
lines.append("")
lines.append("### Key points")
lines.append("- Quick summary exports")
lines.append("- Clinical-note style outputs")
lines.append("- Educational case explanations")
lines.append("- Copyable workflow summaries")
lines.append("")

lines.append("## Feature Page: Case-based learning")
lines.append("")
lines.append("### Headline")
lines.append("Realistic vancomycin dosing cases")
lines.append("")
lines.append("### Subheadline")
lines.append("Explore example scenarios that illustrate interpretation challenges and dosing reasoning.")
lines.append("")
lines.append("### Key points")
lines.append("- Stable monitoring workflow")
lines.append("- Renal instability interpretation")
lines.append("- Sparse level interpretation")
lines.append("- AUC vs trough reasoning")
lines.append("")

lines.append("## Messaging guardrails")
lines.append("")
lines.append("- Avoid unsupported superiority claims")
lines.append("- Emphasize clarity and workflow usability")
lines.append("- Focus on interpretability and transparency")
lines.append("- Maintain clinically cautious tone")

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")

print(f"Wrote {out}")
