/**
 * Watermark utility for Free-tier exports.
 *
 * Centralizes the watermark/banner markup so any export surface
 * (PDF print, future image exports, etc.) can apply consistent
 * Free-tier branding without duplicating the styling rules.
 *
 * Behavior:
 *   - Free tier: tiled diagonal SVG overlay + footer upgrade banner
 *   - Individual Pro / Department / Hospital: nothing
 *
 * Watermark must NOT obscure clinical data — opacity stays low,
 * pointer-events disabled, and a low z-index relative to error/UI
 * overlays. Per regulatory commitments under 21st Century Cures Act
 * §3060 the underlying calculation, equations, and parameters remain
 * fully readable through the watermark.
 */

import { isPaidTier } from "./tiers";

export interface WatermarkOutput {
  /** Inline CSS to splice into the document <style> block. */
  styleCss: string;
  /** HTML overlay div to splice into the document <body>. */
  overlayHtml: string;
  /** Footer banner HTML to splice into the document <body>. */
  bannerHtml: string;
}

const EMPTY: WatermarkOutput = {
  styleCss: "",
  overlayHtml: "",
  bannerHtml: "",
};

/** Return Free-tier watermark markup, or empty strings for paid tiers. */
export function buildExportWatermark(tier: string): WatermarkOutput {
  if (isPaidTier(tier)) return EMPTY;

  // Tiled SVG pattern — 520x180 tile rotated -30°. Repeats over the
  // entire viewport so a printed page never has un-watermarked sections.
  const watermarkSvg =
    "data:image/svg+xml;utf8," +
    "<svg xmlns='http://www.w3.org/2000/svg' width='520' height='180' viewBox='0 0 520 180'>" +
    "<text x='260' y='90' fill='%230d9488' fill-opacity='0.18' font-size='22' " +
    "font-family='Arial,sans-serif' font-weight='600' text-anchor='middle' " +
    "transform='rotate(-30 260 90)'>" +
    "Generated by Vancomyzer™ — vancomyzer.com — Individual Use Only" +
    "</text></svg>";

  const styleCss = `
    .vmz-watermark-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      pointer-events: none;
      z-index: 9999;
      background-image: url("${watermarkSvg}");
      background-repeat: repeat;
      font-size: 0;
      color: transparent;
    }
    .vmz-free-banner {
      margin-top: 16px;
      padding: 8px 12px;
      border: 1px solid #0d9488;
      background: #f0fdfa;
      font-size: 9px;
      color: #115e59;
      text-align: center;
      line-height: 1.5;
    }
    @media print {
      .vmz-watermark-overlay { position: fixed; }
    }
  `.trim();

  // Span text shown ONLY for assistive tech / search engines / accidental
  // clipboard paste — visually-hidden because the SVG carries the brand mark.
  const overlayHtml =
    `<div class="vmz-watermark-overlay" aria-hidden="true">` +
    `Generated by Vancomyzer™ — vancomyzer.com — Individual Use Only` +
    `</div>`;

  const bannerHtml =
    `<div class="vmz-free-banner">` +
    `This calculation was generated using the free tier of Vancomyzer™. ` +
    `Upgrade to remove the watermark and unlock unlimited calculations &amp; history at ` +
    `<a href="https://dosys.health/pricing" style="color:#0d9488">dosys.health/pricing</a>.` +
    `</div>`;

  return { styleCss, overlayHtml, bannerHtml };
}
