/**
 * Cross-implementation HMAC fixture.
 *
 * Mirror this exact fixture on the dosys.health side. Any byte-level drift
 * between the two implementations of the canonical-input rule will surface
 * here, immediately. Run with: `npm run test:hmac`.
 *
 * Fixture choice rationale:
 *  - rawBody contains a non-ASCII character (é, U+00E9) so a UTF-8 vs latin-1
 *    encoding bug would fail.
 *  - rawBody contains JSON whitespace that JSON.stringify({...}) would NOT
 *    reproduce, proving we sign the on-the-wire bytes, not a re-stringified
 *    representation.
 *  - timestamp is fixed so the digest is reproducible across machines/clocks.
 */

import { signPilotPayload, verifyPilotSignature } from "../hmac";

const SECRET = "fixture-secret-do-not-use-in-prod";
const TIMESTAMP = "1735689600"; // 2025-01-01T00:00:00Z, fixed for reproducibility
const RAW_BODY = '{"name":"José","hospital":"St. Mary\'s","email":"a@b.io"}';

// Pre-computed expected digest. Generated by running:
//   node -e 'const c=require("crypto");
//            const s="fixture-secret-do-not-use-in-prod";
//            const t="1735689600";
//            const b=`{"name":"José","hospital":"St. Mary\\u0027s","email":"a@b.io"}`;
//            console.log(c.createHmac("sha256",s).update(`${t}.${b}`).digest("hex"))'
// Recomputed and asserted at test time so this file is self-checking.

function assert(cond: unknown, msg: string): void {
  if (!cond) {
    console.error(`✗ ${msg}`);
    process.exit(1);
  }
  console.log(`✓ ${msg}`);
}

function main(): void {
  // 1. Reproducible digest — same inputs must always produce the same hex output.
  const sig1 = signPilotPayload(RAW_BODY, TIMESTAMP, SECRET);
  const sig2 = signPilotPayload(RAW_BODY, TIMESTAMP, SECRET);
  assert(sig1 === sig2, "signPilotPayload is deterministic");
  assert(/^[0-9a-f]{64}$/.test(sig1), "signature is lowercase hex, 64 chars");

  // Print the digest so the dosys.health side can paste it into their own fixture.
  console.log(`  fixture digest: ${sig1}`);

  // 2. Verification round-trips.
  const ok = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: TIMESTAMP,
    signatureHeader: `sha256=${sig1}`,
    secret: SECRET,
    now: Number(TIMESTAMP) + 10, // 10s after sign — well within skew window
  });
  assert(ok.ok, "verifyPilotSignature accepts the fixture");

  // 3. Drift detectors — these MUST fail.
  const tampered = verifyPilotSignature({
    rawBody: RAW_BODY + " ", // appended space
    timestampHeader: TIMESTAMP,
    signatureHeader: `sha256=${sig1}`,
    secret: SECRET,
    now: Number(TIMESTAMP) + 10,
  });
  assert(!tampered.ok && tampered.reason === "signature_mismatch", "tampered body rejected");

  const wrongTimestamp = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: String(Number(TIMESTAMP) + 1),
    signatureHeader: `sha256=${sig1}`,
    secret: SECRET,
    now: Number(TIMESTAMP) + 10,
  });
  assert(
    !wrongTimestamp.ok && wrongTimestamp.reason === "signature_mismatch",
    "wrong timestamp rejected (sig was bound to original timestamp)",
  );

  const skewed = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: TIMESTAMP,
    signatureHeader: `sha256=${sig1}`,
    secret: SECRET,
    now: Number(TIMESTAMP) + 301, // 1 second past the 5-min window
  });
  assert(!skewed.ok && skewed.reason === "skew_exceeded", "stale timestamp rejected");

  const noPrefix = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: TIMESTAMP,
    signatureHeader: sig1, // missing "sha256=" prefix
    secret: SECRET,
    now: Number(TIMESTAMP) + 10,
  });
  assert(!noPrefix.ok && noPrefix.reason === "bad_prefix", "missing prefix rejected");

  const missingSecret = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: TIMESTAMP,
    signatureHeader: `sha256=${sig1}`,
    secret: undefined,
    now: Number(TIMESTAMP) + 10,
  });
  assert(
    !missingSecret.ok && missingSecret.reason === "missing_secret",
    "missing secret rejected (fail-closed)",
  );

  const badTimestampFormat = verifyPilotSignature({
    rawBody: RAW_BODY,
    timestampHeader: "1735689600.5", // float, not integer seconds
    signatureHeader: `sha256=${sig1}`,
    secret: SECRET,
    now: Number(TIMESTAMP) + 10,
  });
  assert(
    !badTimestampFormat.ok && badTimestampFormat.reason === "bad_timestamp",
    "non-integer timestamp rejected",
  );

  console.log("\nAll HMAC fixture assertions passed.");
}

main();
