import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      title: 'Vancomyzer®',
      slogan: 'Interactive Evidence-Based Vancomycin Dosing Calculator',
      disclaimers: {
        hero: 'For healthcare professionals only. Educational purposes — not a substitute for clinical judgment.',
        calculator: 'Disclaimer: This tool is provided for informational and educational purposes only. It does not replace independent clinical judgment. Always verify calculations and follow institutional protocols.',
        pdf: "Disclaimer: Generated by Vancomyzer®. For educational use only. Verify with institutional policies before applying clinically.",
        footer: '© {{year}} Vancomyzer®. All rights reserved. Vancomyzer® is provided \'as-is\' without any warranty. The developers are not liable for clinical outcomes. Consult ASHP/IDSA guidelines and your institution’s policies.'
      },
      legal: {
        link: 'Terms & Privacy',
        title: 'Terms & Privacy',
        intendedUse: { title: 'Intended Use', body: 'Vancomyzer® is intended for use by licensed healthcare professionals for educational and informational purposes to support vancomycin dosing concepts. It is not a substitute for professional medical advice, diagnosis, or treatment.' },
        medicalDisclaimer: { title: 'Medical Disclaimer', body: 'Clinical decisions must be based on independent clinical judgment and patient-specific factors. Always verify calculations and consult institutional policies and current ASHP/IDSA guidelines before applying recommendations in practice.' },
        liability: { title: 'Limitations of Liability', body: 'Vancomyzer® is provided "as-is" without warranties of any kind. The developers and contributors shall not be liable for any direct, indirect, incidental, or consequential damages resulting from use of the app or website.' },
        privacy: { title: 'Privacy & Data Handling', body: 'Vancomyzer® does not collect protected health information (PHI). Input data may be processed locally or via secured endpoints for computation. Do not enter personally identifiable information. See repository documentation for technical details.' }
      },
      bullets: {
        guidelines: 'Following ASHP/IDSA 2020 Guidelines',
        realtimeAuc: 'Real-time AUC Visualization',
        bayesian: 'Bayesian Optimization'
      },
      tabs: {
        adult: 'Adult',
        pediatric: 'Pediatric',
        neonate: 'Neonate',
        interactiveAuc: 'Interactive AUC',
        clinicalInfo: 'Clinical Info'
      },
      badges: {
        evidenceBased: 'Evidence-based',
        bayesianOptimization: 'Bayesian optimization'
      },
      buttons: { guidelines: 'Guidelines' },
      app: { title: 'Vancomyzer®', subtitle: '', tagline: '' },
      nav: { interactive_auc: 'Interactive AUC', clinical_info: 'Clinical Info' },
      patient: 'Patient',
      age: 'Age',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      weight: 'Weight',
      height: 'Height',
      scr: 'SCr',
      mic: 'MIC',
      auc24: 'AUC24',
      predicted_trough: 'Predicted trough',
      predicted_peak: 'Predicted peak',
      dose: 'Dose',
      interval: 'Interval',
      infusion: 'Infusion',
      shade_auc: 'Shade 0–24h AUC',
      show_dose_markers: 'Show dose markers',
      bayesian: 'Bayesian',
      updating: 'Updating…',
      copy_json: 'Copy JSON',
      export_pdf: 'Export PDF',
      measured_levels: 'Measured Levels',
      mode: 'Mode',
      no_levels: 'No levels',
      one_level_bayesian: 'One level (Bayesian)',
      two_levels_peak_trough: 'Two levels (peak + trough)',
      peak_random: 'Peak/random',
      hours_after_infusion_end: 'Hours after infusion end',
      trough: 'Trough',
      trough_time: 'Trough time',
      hours: 'Hours',
      concentration: 'Concentration'
    }
  },
  es: {
    translation: {
      title: 'Vancomyzer®',
      slogan: 'Calculadora interactiva de dosificación de vancomicina basada en evidencia',
      disclaimers: {
        hero: 'Solo para profesionales de la salud. Con fines educativos — no sustituye el juicio clínico.',
        calculator: 'Descargo de responsabilidad: Esta herramienta se proporciona con fines informativos y educativos. No reemplaza el juicio clínico independiente. Verifique siempre los cálculos y siga los protocolos institucionales.',
        pdf: 'Descargo: Generado por Vancomyzer®. Solo para uso educativo. Verifique con las políticas de su institución antes de aplicarlo clínicamente.',
        footer: '© {{year}} Vancomyzer®. Todos los derechos reservados. Vancomyzer® se proporciona “tal cual”, sin ninguna garantía. Los desarrolladores no son responsables de los resultados clínicos. Consulte las guías ASHP/IDSA y las políticas de su institución.'
      },
      legal: {
        link: 'Términos y Privacidad',
        title: 'Términos y Privacidad',
        intendedUse: { title: 'Uso previsto', body: 'Vancomyzer® está destinado a profesionales de la salud con fines educativos e informativos para apoyar conceptos de dosificación de vancomicina. No sustituye el consejo, diagnóstico o tratamiento médico profesional.' },
        medicalDisclaimer: { title: 'Descargo de responsabilidad médica', body: 'Las decisiones clínicas deben basarse en el juicio clínico independiente y en factores específicos del paciente. Verifique siempre los cálculos y consulte las políticas institucionales y las guías ASHP/IDSA vigentes antes de aplicar recomendaciones en la práctica.' },
        liability: { title: 'Limitación de responsabilidad', body: 'Vancomyzer® se proporciona “tal cual” sin garantías de ningún tipo. Los desarrolladores y colaboradores no serán responsables por daños directos o indirectos derivados del uso de la aplicación o del sitio web.' },
        privacy: { title: 'Privacidad y manejo de datos', body: 'Vancomyzer® no recopila información de salud protegida (PHI). Los datos ingresados pueden procesarse localmente o mediante endpoints seguros para el cálculo. No ingrese información de identificación personal.' }
      },
      bullets: {
        guidelines: 'Siguiendo las guías ASHP/IDSA 2020',
        realtimeAuc: 'Visualización de AUC en tiempo real',
        bayesian: 'Optimización bayesiana'
      },
      tabs: {
        adult: 'Adulto',
        pediatric: 'Pediátrico',
        neonate: 'Neonato',
        interactiveAuc: 'AUC Interactiva',
        clinicalInfo: 'Información clínica'
      },
      badges: {
        evidenceBased: 'Basado en evidencia',
        bayesianOptimization: 'Optimización bayesiana'
      },
      buttons: { guidelines: 'Guías' },
      app: { title: 'Vancomyzer®', subtitle: '', tagline: '' },
      nav: { interactive_auc: 'AUC interactivo', clinical_info: 'Información clínica' },
      patient: 'Paciente',
      age: 'Edad',
      gender: 'Sexo',
      male: 'Hombre',
      female: 'Mujer',
      weight: 'Peso',
      height: 'Altura',
      scr: 'SCr',
      mic: 'MIC',
      auc24: 'AUC24',
      predicted_trough: 'Valle previsto',
      predicted_peak: 'Pico previsto',
      dose: 'Dosis',
      interval: 'Intervalo',
      infusion: 'Infusión',
      shade_auc: 'Sombrear AUC 0–24h',
      show_dose_markers: 'Mostrar marcadores de dosis',
      bayesian: 'Bayesiano',
      updating: 'Actualizando…',
      copy_json: 'Copiar JSON',
      export_pdf: 'Exportar PDF',
      measured_levels: 'Niveles medidos',
      mode: 'Modo',
      no_levels: 'Sin niveles',
      one_level_bayesian: 'Un nivel (Bayesiano)',
      two_levels_peak_trough: 'Dos niveles (pico + valle)',
      peak_random: 'Pico/aleatorio',
      hours_after_infusion_end: 'Horas después del fin de la infusión',
      trough: 'Valle',
      trough_time: 'Tiempo de valle',
      hours: 'Horas',
      concentration: 'Concentración'
    }
  },
  ar: {
    translation: {
      title: 'فانكومايزر®',
      slogan: 'حاسبة تفاعلية لجرعات الفانكومايسين قائمة على الأدلة',
      disclaimers: {
        hero: 'مخصص لمهنيي الرعاية الصحية فقط. لأغراض تعليمية — وليس بديلاً عن الحكم السريري.',
        calculator: 'إخلاء مسؤولية: تُقدَّم هذه الأداة لأغراض معلوماتية وتعليمية فقط. لا تُغني عن الحكم السريري المستقل. يرجى دائماً التحقق من الحسابات واتباع سياسات المؤسسة.',
        pdf: 'إخلاء: تم إنشاء المستند بواسطة فانكومايزر®. للاستخدام التعليمي فقط. تحقّق من سياسات مؤسستك قبل التطبيق سريرياً.',
        footer: '© {{year}} فانكومايزر®. جميع الحقوق محفوظة. يُقدَّم فانكومايزر® "كما هو" دون أي ضمان. لا يتحمل المطورون مسؤولية النتائج السريرية. يُرجى الرجوع إلى إرشادات ASHP/IDSA وسياسات مؤسستك.'
      },
      legal: {
        link: 'الشروط والخصوصية',
        title: 'الشروط والخصوصية',
        intendedUse: { title: 'الغرض المقصود', body: 'فانكومايزر® موجّه للمهنيين المرخصين في الرعاية الصحية لأغراض تعليمية ومعلوماتية لدعم مفاهيم جرعات الفانكومايسين. ليس بديلاً عن النصيحة أو التشخيص أو العلاج الطبي.' },
        medicalDisclaimer: { title: 'إخلاء المسؤولية الطبية', body: 'يجب أن تستند القرارات السريرية إلى الحكم السريري المستقل وعوامل المريض الخاصة. تحقّق دائماً من الحسابات واستشر سياسات المؤسسة وإرشادات ASHP/IDSA الحالية قبل التطبيق العملي.' },
        liability: { title: 'حدود المسؤولية', body: 'يُقدَّم فانكومايزر® "كما هو" دون أي ضمانات. لا يتحمل المطورون والمساهمون أي مسؤولية عن الأضرار الناتجة عن استخدام التطبيق أو الموقع.' },
        privacy: { title: 'الخصوصية ومعالجة البيانات', body: 'لا يجمع فانكومايزر® معلومات صحية محمية (PHI). قد تتم معالجة البيانات المدخلة محلياً أو عبر نقاط نهاية آمنة للحساب. يُرجى عدم إدخال معلومات تعريف شخصية.' }
      },
      bullets: {
        guidelines: 'وفق إرشادات ASHP/IDSA لعام 2020',
        realtimeAuc: 'تصوير فوري لمساحة تحت المنحنى',
        bayesian: 'تحسين بايزي'
      },
      tabs: {
        adult: 'بالغ',
        pediatric: 'أطفال',
        neonate: 'حديثو الولادة',
        interactiveAuc: 'AUC تفاعلي',
        clinicalInfo: 'معلومات سريرية'
      },
      badges: {
        evidenceBased: 'قائم على الأدلة',
        bayesianOptimization: 'تحسين بايزي'
      },
      buttons: { guidelines: 'الإرشادات' },
      app: { title: 'فانكومايزر®', subtitle: '', tagline: '' },
      nav: { interactive_auc: 'AUC تفاعلي', clinical_info: 'معلومات سريرية' },
      patient: 'المريض',
      age: 'العمر',
      gender: 'الجنس',
      male: 'ذكر',
      female: 'أنثى',
      weight: 'الوزن',
      height: 'الطول',
      scr: 'الكرياتينين المصلي',
      mic: 'MIC',
      auc24: 'AUC24',
      predicted_trough: 'القاع المتوقع',
      predicted_peak: 'الذروة المتوقعة',
      dose: 'الجرعة',
      interval: 'الفاصل',
      infusion: 'التسريب',
      shade_auc: 'تظليل AUC 0–24 ساعة',
      show_dose_markers: 'إظهار علامات الجرعات',
      bayesian: 'بايزي',
      updating: 'جارٍ التحديث…',
      copy_json: 'نسخ JSON',
      export_pdf: 'تصدير PDF',
      measured_levels: 'المستويات المقاسة',
      mode: 'الوضع',
      no_levels: 'لا توجد مستويات',
      one_level_bayesian: 'مستوى واحد (بايزي)',
      two_levels_peak_trough: 'مستويان (ذروة + قاع)',
      peak_random: 'ذروة/عشوائي',
      hours_after_infusion_end: 'الساعات بعد نهاية التسريب',
      trough: 'القاع',
      trough_time: 'وقت القاع',
      hours: 'الساعات',
      concentration: 'التركيز'
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
    detection: {
      order: ['querystring', 'localStorage', 'navigator'],
      caches: ['localStorage']
    }
  });

export default i18n;
